language: php
php:
  - 5.3
  - 5.4
before_install:
  - cd ../
  - git clone git://github.com/UnionOfRAD/framework.git
  - cp -fr li3_redis/tests/data/connections.php framework/app/config/bootstrap/connections.php
  - sed -i -e 's|// Libraries::add('li3_docs');|Libraries::add('li3_redis');|' framework/app/config/bootstrap/libraries.php
  - mv li3_redis/ framework/app/libraries/li3_redis
  - cd framework
  - git submodule update --init --recursive
  - cd libraries/lithium && git pull --rebase origin master
  - cd ../../app/libraries/li3_redis
  - wget https://github.com/nicolasff/phpredis/archive/master.zip -O php-redis.zip && unzip php-redis.zip
  - cd phpredis-master/ && phpize && ./configure && make && make install
  - echo "extension=redis.so" > redis.ini && phpenv config-add redis.ini
  - cd ..
  - echo "extension=/home/travis/build/bruensicke/framework/app/libraries/li3_redis/phpredis-master/modules/redis.so" >> ~/.phpenv/versions/$(phpenv version-name)/etc/php.ini
  - phpenv rehash
script: ../../../libraries/lithium/console/li3 test tests
