language: php
php:
  - 5.3
  - 5.4
services:
  - redis-server
# env:
#   - REDIS_STANDALONE=0
#   - REDIS_STANDALONE=1
before_install:
  - cd ../
  - git clone git://github.com/UnionOfRAD/framework.git
  - cp -fr li3_redis/tests/data/connections.php framework/app/config/bootstrap/connections.php
  - sed -i -e 's|// Libraries::add('li3_docs');|Libraries::add('li3_redis');|' framework/app/config/bootstrap/libraries.php
  - mv li3_redis/ framework/app/libraries/li3_redis
  - cd framework
  - git submodule update --init --recursive
  - cd libraries/lithium && git pull --rebase origin master
  - cd ../../app/libraries/li3_redis
  - pecl install redis
  - echo "extension=redis.so" >> `php --ini | grep "Loaded Configuration" | sed -e "s|.*:\s*||"`

script: ../../../libraries/lithium/console/li3 test tests
