language: php
php:
  - 5.3
  - 5.4
services:
  - redis-server
# env:
#   - REDIS_STANDALONE=0
#   - REDIS_STANDALONE=1
before_install:
  # - php tests/ci_depends.php
  - cd ../
  - git clone git://github.com/UnionOfRAD/framework.git
  - cp -fr li3_redis/tests/data/connections.php framework/app/config/bootstrap/connections.php
  - sed -i -e 's|// Libraries::add('li3_docs');|Libraries::add('li3_redis');|' framework/app/config/bootstrap/libraries.php
  - mv li3_redis/ framework/app/libraries/li3_redis
  - cd framework
  - git submodule update --init --recursive
  - cd libraries/lithium && git pull --rebase origin master
  - cd ../../app/libraries/li3_redis
  - wget https://github.com/nicolasff/phpredis/archive/2.2.2.zip -O php-redis.zip && unzip php-redis.zip
  - cd phpredis-2.2.2/ && phpize && ./configure && make && make install
  - echo "extension=redis.so" > redis.ini && phpenv config-add redis.ini
  - cd ..
  - echo "extension=/home/travis/build/bruensicke/framework/app/libraries/li3_redis/phpredis-2.2.2/modules/redis.so" >> ~/.phpenv/versions/$(phpenv version-name)/etc/php.ini
  - phpenv rehash
# before_script:
#   - sh -c "if [ $REDIS_STANDALONE -eq 0 ]; then wget https://github.com/nicolasff/phpredis/archive/2.2.2.zip -O php-redis.zip && unzip php-redis.zip; fi"
#   - sh -c "if [ $REDIS_STANDALONE -eq 0 ]; then cd phpredis-2.2.2/ && phpize && ./configure && make && make install; fi"
#   - sh -c "if [ $REDIS_STANDALONE -eq 0 ]; then echo \"extension=redis.so\" >> `php --ini | grep \"Loaded Configuration\" | sed -e \"s|.*:\s*||\"`; fi"
script: ../../../libraries/lithium/console/li3 test tests
