language: php
php:
  - 5.3
  - 5.4
before_install:
  # install phpredis extension.
  - wget -O phpredis.tar.gz --no-check-certificate https://github.com/nicolasff/phpredis/tarball/master
  - tar -xzf phpredis.tar.gz
  - sh -c "cd nicolasff-phpredis-* && phpize && ./configure && make && sudo make install"
  - echo "extension=redis.so" > redis.ini && phpenv config-add redis.ini
before_script:
  # install lithium
  - cd ../
  - git clone git://github.com/UnionOfRAD/framework.git
  - sed -i -e 's|// Libraries::add('li3_docs');|Libraries::add('li3_redis');|' framework/app/config/bootstrap/libraries.php
  - mv li3_redis/ framework/app/libraries/li3_redis
  - cd framework
  - git submodule update --init --recursive
  - cd libraries/lithium && git pull --rebase origin master
  - cd ../../app/libraries/li3_redis
script: ../../../libraries/lithium/console/li3 test tests
